title: Jinming Hu's Homepage
page-top-title: Jinming Hu
top-section-bg-text: Applied Mathematics (Cybernatics)
home-subtitle: Jinming Hu&ensp;|&ensp;胡锦明
copyright-text: '&copy; Jinming Hu 2024-2025. All Rights Reserved.'
