title: Jinming Hu's Homepage
page-top-title: Jinming Hu
top-section-bg-text: Applied Mathematics (Cybernetics)
home-subtitle: Jinming Hu&ensp;|&ensp;胡锦明
copyright-text: '&copy; Jinming Hu 2025-2026. All Rights Reserved.'
